package org.nnstd.compose.icons.mdi

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MaterialDesignIcons.ViewGridCompact: ImageVector
    get() {
        if (_ViewGridCompact != null) {
            return _ViewGridCompact!!
        }
        _ViewGridCompact = ImageVector.Builder(
            name = "ViewGridCompact",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                moveTo(2f, 5f)
                horizontalLineTo(4f)
                verticalLineTo(7f)
                horizontalLineTo(2f)
                verticalLineTo(5f)
                moveTo(5f, 5f)
                horizontalLineTo(7f)
                verticalLineTo(7f)
                horizontalLineTo(5f)
                verticalLineTo(5f)
                moveTo(8f, 5f)
                horizontalLineTo(10f)
                verticalLineTo(7f)
                horizontalLineTo(8f)
                verticalLineTo(5f)
                moveTo(11f, 5f)
                horizontalLineTo(13f)
                verticalLineTo(7f)
                horizontalLineTo(11f)
                verticalLineTo(5f)
                moveTo(14f, 5f)
                horizontalLineTo(16f)
                verticalLineTo(7f)
                horizontalLineTo(14f)
                verticalLineTo(5f)
                moveTo(17f, 5f)
                horizontalLineTo(19f)
                verticalLineTo(7f)
                horizontalLineTo(17f)
                verticalLineTo(5f)
                moveTo(20f, 5f)
                horizontalLineTo(22f)
                verticalLineTo(7f)
                horizontalLineTo(20f)
                verticalLineTo(5f)
                moveTo(2f, 8f)
                horizontalLineTo(4f)
                verticalLineTo(10f)
                horizontalLineTo(2f)
                verticalLineTo(8f)
                moveTo(5f, 8f)
                horizontalLineTo(7f)
                verticalLineTo(10f)
                horizontalLineTo(5f)
                verticalLineTo(8f)
                moveTo(8f, 8f)
                horizontalLineTo(10f)
                verticalLineTo(10f)
                horizontalLineTo(8f)
                verticalLineTo(8f)
                moveTo(11f, 8f)
                horizontalLineTo(13f)
                verticalLineTo(10f)
                horizontalLineTo(11f)
                verticalLineTo(8f)
                moveTo(14f, 8f)
                horizontalLineTo(16f)
                verticalLineTo(10f)
                horizontalLineTo(14f)
                verticalLineTo(8f)
                moveTo(17f, 8f)
                horizontalLineTo(19f)
                verticalLineTo(10f)
                horizontalLineTo(17f)
                verticalLineTo(8f)
                moveTo(20f, 8f)
                horizontalLineTo(22f)
                verticalLineTo(10f)
                horizontalLineTo(20f)
                verticalLineTo(8f)
                moveTo(2f, 11f)
                horizontalLineTo(4f)
                verticalLineTo(13f)
                horizontalLineTo(2f)
                verticalLineTo(11f)
                moveTo(5f, 11f)
                horizontalLineTo(7f)
                verticalLineTo(13f)
                horizontalLineTo(5f)
                verticalLineTo(11f)
                moveTo(8f, 11f)
                horizontalLineTo(10f)
                verticalLineTo(13f)
                horizontalLineTo(8f)
                verticalLineTo(11f)
                moveTo(11f, 11f)
                horizontalLineTo(13f)
                verticalLineTo(13f)
                horizontalLineTo(11f)
                verticalLineTo(11f)
                moveTo(14f, 11f)
                horizontalLineTo(16f)
                verticalLineTo(13f)
                horizontalLineTo(14f)
                verticalLineTo(11f)
                moveTo(17f, 11f)
                horizontalLineTo(19f)
                verticalLineTo(13f)
                horizontalLineTo(17f)
                verticalLineTo(11f)
                moveTo(20f, 11f)
                horizontalLineTo(22f)
                verticalLineTo(13f)
                horizontalLineTo(20f)
                verticalLineTo(11f)
                moveTo(2f, 14f)
                horizontalLineTo(4f)
                verticalLineTo(16f)
                horizontalLineTo(2f)
                verticalLineTo(14f)
                moveTo(5f, 14f)
                horizontalLineTo(7f)
                verticalLineTo(16f)
                horizontalLineTo(5f)
                verticalLineTo(14f)
                moveTo(8f, 14f)
                horizontalLineTo(10f)
                verticalLineTo(16f)
                horizontalLineTo(8f)
                verticalLineTo(14f)
                moveTo(11f, 14f)
                horizontalLineTo(13f)
                verticalLineTo(16f)
                horizontalLineTo(11f)
                verticalLineTo(14f)
                moveTo(14f, 14f)
                horizontalLineTo(16f)
                verticalLineTo(16f)
                horizontalLineTo(14f)
                verticalLineTo(14f)
                moveTo(17f, 14f)
                horizontalLineTo(19f)
                verticalLineTo(16f)
                horizontalLineTo(17f)
                verticalLineTo(14f)
                moveTo(20f, 14f)
                horizontalLineTo(22f)
                verticalLineTo(16f)
                horizontalLineTo(20f)
                verticalLineTo(14f)
                moveTo(2f, 17f)
                horizontalLineTo(4f)
                verticalLineTo(19f)
                horizontalLineTo(2f)
                verticalLineTo(17f)
                moveTo(5f, 17f)
                horizontalLineTo(7f)
                verticalLineTo(19f)
                horizontalLineTo(5f)
                verticalLineTo(17f)
                moveTo(8f, 17f)
                horizontalLineTo(10f)
                verticalLineTo(19f)
                horizontalLineTo(8f)
                verticalLineTo(17f)
                moveTo(11f, 17f)
                horizontalLineTo(13f)
                verticalLineTo(19f)
                horizontalLineTo(11f)
                verticalLineTo(17f)
                moveTo(14f, 17f)
                horizontalLineTo(16f)
                verticalLineTo(19f)
                horizontalLineTo(14f)
                verticalLineTo(17f)
                moveTo(17f, 17f)
                horizontalLineTo(19f)
                verticalLineTo(19f)
                horizontalLineTo(17f)
                verticalLineTo(17f)
                moveTo(20f, 17f)
                horizontalLineTo(22f)
                verticalLineTo(19f)
                horizontalLineTo(20f)
                verticalLineTo(17f)
            }
        }.build()

        return _ViewGridCompact!!
    }

@Suppress("ObjectPropertyName")
private var _ViewGridCompact: ImageVector? = null
